version: '3'
networks:
  default:
    driver: bridge

services:
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    container_name: game-webserver
    ports:
      - "8000:8000"
    volumes:
      - ./apps/game/:/var/www/game
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/ssl/
    extra_hosts: # <-- does no harm
      - "host.docker.internal:host-gateway" # <-- does no harm
  game:
    container_name: game-service
    build:
      context: apps/game
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/game
    env_file:
      - .env
    volumes:
      - ./apps/game/:/var/www/game
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    extra_hosts: # <--- this is required
      - "host.docker.internal:host-gateway" # <--- this is required`
  gateway_db:
    container_name: game-db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/game-db/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${GAME_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${GAME_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${GAME_MONGO_DATABASE}
  redis:
    image: redis
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
